language: node_js
node_js:
- "11.10.1"
sudo: true
before_script: curl https://rclone.org/install.sh | sudo bash
jobs:
  include:
  - name: dev
    if: "(branch = master) or (tag =~ ^v)"
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    - rclone copy dist :s3://auth/form/dev/ --s3-access-key-id=$MINIO_S3_ACCESS_KEY --s3-secret-access-key=$MINIO_S3_SECRET_KEY --s3-endpoint=$MINIO_S3_HOST
  - name: dev
    if: "(branch = develop)"
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    - rclone copy dist :s3://auth/form/develop/ --s3-access-key-id=$MINIO_S3_ACCESS_KEY --s3-secret-access-key=$MINIO_S3_SECRET_KEY --s3-endpoint=$MINIO_S3_HOST
  - name: release
    if: "(tag =~ ^v)"
    script:
    - set -e
    - npm run lint
    - npm run test
    - npm run build
    - rclone copy dist :s3://auth/form/latest/ --s3-access-key-id=$MINIO_S3_ACCESS_KEY --s3-secret-access-key=$MINIO_S3_SECRET_KEY --s3-endpoint=$MINIO_S3_HOST
    - rclone copy dist :s3://auth/form/$TRAVIS_TAG/ --s3-access-key-id=$MINIO_S3_ACCESS_KEY --s3-secret-access-key=$MINIO_S3_SECRET_KEY --s3-endpoint=$MINIO_S3_HOST
    - rclone copy dist :s3://cdn-auth-super-com/authform/latest/ --s3-access-key-id=$AWS_CDN_ACCESS_KEY_ID --s3-secret-access-key=$AWS_CDN_ACCESS_SECRET_KEY --s3-region=eu-west-1
    - rclone copy dist :s3://cdn-auth-super-com/authform/$TRAVIS_TAG/ --s3-access-key-id=$AWS_CDN_ACCESS_KEY_ID --s3-secret-access-key=$AWS_CDN_ACCESS_SECRET_KEY --s3-region=eu-west-1
notifications:
  email: false
  slack:
    secure: AEx0melqLH4YofPkQj/Wc81TH1zM9vUT7N9Zg8C20BG+xrodBnp9i9fO2vUrtz0FErBKakq/0PuDYlH/4qLKAmDMuJ7LDB0OWwM5G/wSUw6atHtNMzprDG/JbQOxjDr0IGvMltoAprc6NRo6dRzLwVvTtLFT0Ot3fbcOBhhph8pIGPGw3aSKwcYZQ0cAJboBRu2qiqUWXfKY5UIvlIgBFkphZdnw2fotuIbueConyeBz86yde2ulFdfw8zU3tNOQLLpAmz6RnR6TRenXHGdv8km8HYTDuPiyli56TXj2hWYTCFYV7cJFcvH63F55xp1h98MTlmxc5uBMz+hWN1embMeGTq+cUnI/TjjBklOPsRxMB9GRbAP2q6s4rzvtaklml5a6OOEwb0Yw4NeUXfqpL/jcOzzru42TaLQcNGgxdkxJLtK1K933H7Q2VygnDU9lfWCbQzSZMuvambRmgZCs4/Mb1YROH20aM6v1GgR9QpjI/2SbP25R+j8Dyltc/zvPnATCeIpHvZGgsiNH1camPD3QKqsHyrmm1pA79UXhw4Oobv7erfbTFYop9+FuikASmN9ZTrqkuzd3nW4nzQGCKAMU5esCiCx9mwwz3HBAaDnvEQIGxhdpXJHKgV3hNH466JKQ8U4T7rLGHp4GzT/8lMG69XwU+nFA6TBZO/M7V98=
